;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	Buffer-menu-delete
	Buffer-menu-delete-backwards
	Buffer-menu-execute
	beginning-of-buffer
	copilot-accept-completion
	drag-stuff-up
	duplicate-current-line
	indent-for-tab-command
	kill-region
	magit-diff
	markdown-outdent-or-delete
	org-beginning-of-line
	org-cycle
	org-delete-char
	org-end-of-line
	org-force-self-insert
	org-return
	org-self-insert-command
	org-yank
	rjsx-delete-creates-full-tag
	sgml-slash
	undefined
	undo-redo
	upcase-region
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-visual-line
	electric-newline-and-maybe-indent
	end-of-visual-line
	mark-whole-buffer
	markdown-enter-key
	))
